CapstoneProject/Models/Employee.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace CapstoneProject.Models
{
    public class Employee
    {
        private const int MAX_NAME_LENGTH = 50;

        [Display(Name = "Employee ID")]
        [Range(0, int.MaxValue, ErrorMessage = "ID must be a non-negative whole number")]
        [Required(ErrorMessage = "Employee must have ID")]
        public int EmployeeID { get; set; }

        [Display(Name = "First")]
        [StringLength(MAX_NAME_LENGTH)]
        [Required(ErrorMessage = "Employee must have first name")]
        public string FirstName { get; set; }

        [Display(Name = "Last")]
        [StringLength(MAX_NAME_LENGTH)]
        [Required(ErrorMessage = "Employee must have last name")]
        public string LastName { get; set; }

        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Display(Name = "Address")]
        [Required(ErrorMessage = "Employee must have address")]
        public string Address { get; set; }

        [Display(Name = "Phone")]
        [Required(ErrorMessage = "Phone number required")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        public int? CohortID { get; set; }

        public virtual Cohort Cohort { get; set; }

        public virtual ICollection<Evaluation> Evaluations { get; set; }

        public bool EmailConfirmed { get; set; }
    }
}

CapstoneProject/Controllers/EmployeesController.cs
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CapstoneProject.DAL;
using CapstoneProject.Models;
using LumenWorks.Framework.IO.Csv;
using Microsoft.AspNet.Identity.Owin;

namespace CapstoneProject.Controllers
{
    [Authorize(Roles = "Admin")]
    [HandleError]
    public class EmployeesController : Controller
    {
        private IUnitOfWork unitOfWork = new UnitOfWork();
        private DataTable csvTable = new DataTable();
        private ApplicationDbContext dbUser = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;

        public IUnitOfWork UnitOfWork
        {
            get
            {
                return this.unitOfWork;
            }
            set
            {
                this.unitOfWork = value;
            }
        }

        public EmployeesController()
        {

        }

        public EmployeesController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        public ApplicationSignInManager SignInManager
        {
            get { return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>(); }
            private set { _signInManager = value; }
        }

        // GET: Employees
        public ActionResult Index()
        {
            var employees = unitOfWork.EmployeeRepository.Get().OrderBy(e => e.LastName);
            return View("Index", employees.ToList());
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = unitOfWork.EmployeeRepository.GetByID(id);
            if (employee == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View("Details", employee);
        }

        public ActionResult UploadData()
        {
            return View("UploadData");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UploadData(HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {

                    if (upload.FileName.EndsWith(".csv"))
                    {
                        var stream = upload.InputStream;
                        using (var csvReader =
                            new CsvReader(new StreamReader(stream), true))
                        {
                            csvTable.Load(csvReader);
                        }
                        await InsertCsvDataIntoDb();
                        return View(csvTable);
                    }
                    ModelState.AddModelError("File", "This file format is not supported.\r\n\r\nPlease upload a .csv file.");
                    return View();
                }
                ModelState.AddModelError("File", "Please Upload Your file");
            }
            return View();
        }

        private async Task InsertCsvDataIntoDb()
        {
            var duplicates = "";
            for (var i = 0; i < csvTable.Rows.Count; i++)
            {
                var isDuplicate = false;
                var firstName = csvTable.Rows[i][0].ToString();
                var lastName = csvTable.Rows[i][1].ToString();
                var email = csvTable.Rows[i][2].ToString();
                var address = csvTable.Rows[i][3].ToString();
                var phone = csvTable.Rows[i][4].ToString();

                if (unitOfWork.EmployeeRepository.Get().Any(e => e.Email.Equals(email)) ||
                    dbUser.Users.Any(u => u.Email.Equals(email)))
                {
                    isDuplicate = true;
                }

                // Remove duplicate emails from displayed table. Will need to change if csv format changes (if email is moved).
                if (isDuplicate)
                {
                    csvTable.Rows.Remove(csvTable.Rows[i]);
                    duplicates += firstName + " " + lastName + ", ";
                    i--; // Since row[0] was just deleted, row[1] became row[0], so move i back.
                    continue;
                }
                var e1 = new Employee
                {
                    FirstName = firstName,
                    LastName = lastName,
                    Email = email,
                    Address = address,
                    Phone = phone
                };
                var u1 = new ApplicationUser
                {
                    Email = e1.Email,
                    UserName = e1.Email,
                    PhoneNumber = e1.Phone
                };
                
                dbUser.Users.Add(u1);
                unitOfWork.EmployeeRepository.Insert(e1);
                dbUser.SaveChanges();
                unitOfWork.Save();
            }

            if (!string.IsNullOrEmpty(duplicates))
            {
                ViewBag.Duplicates = "The following duplicates were skipped: " +
                    duplicates.Substring(0, duplicates.Length - 2) + ".";
            }
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var employee = unitOfWork.EmployeeRepository.GetByID(id);
            if (employee == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //ViewBag.CohortID = new SelectList(unitOfWork.CohortRepository.Get(), "CohortID", "Name", employee.CohortID);
            return View("Edit", employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeID,FirstName,LastName,Email,Address,Phone")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.EmployeeRepository.Update(employee);
                unitOfWork.Save();
                TempData["EditSuccess"] = "Edited Employee: " + employee.FirstName + " " + employee.LastName + ".";
                return RedirectToAction("Index");
            }
            //ViewBag.CohortID = new SelectList(unitOfWork.CohortRepository.Get(), "CohortID", "Name", employee.CohortID);
            return View("Edit", employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = unitOfWork.EmployeeRepository.GetByID(id);
            if (employee == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View("Delete", employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var employee = unitOfWork.EmployeeRepository.GetByID(id);
            if (employee == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }        

            var aspNetUser = dbUser.Users.Single(a => a.Email.Equals(employee.Email));
            dbUser.Users.Remove(aspNetUser);
            dbUser.SaveChanges();

            var cohort = unitOfWork.CohortRepository.GetByID(employee.CohortID); 
            if (cohort != null)
            {
                cohort.Employees.Remove(employee);
                UnitOfWork.Save();
                if (cohort.Employees.Count == 0)
                {
                    cohort.Type1Assigned = false;
                    cohort.Type2Assigned = false;
                }
            }

            unitOfWork.EmployeeRepository.Delete(employee);
            unitOfWork.Save();

            TempData["DeleteSuccess"] = "Deleted Employee: " + employee.FirstName + " " + employee.LastName + ".";
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> SendPasswordCreationEmail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var employee = UnitOfWork.EmployeeRepository.GetByID(id);
            if (employee == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = await UserManager.FindByNameAsync(employee.Email);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var email = user.Email;
            var callbackUrl = Url.Action("CreatePassword", "Account", new { userId = user.Id, email },

CapstoneProject/Views/Employees/Delete.cshtml
@model CapstoneProject.Models.Employee

@{
    ViewBag.Title = "Delete | " + Model.FirstName + " " + Model.LastName;
}

<h2>Delete Employee</h2>
<h4>Are you sure you want to delete @Model.FirstName @Model.LastName?</h4>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            Cohort
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cohort.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete Employee" class="btn btn-default" />
            </div>
        </div>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CapstoneProject/Views/Employees/Details.cshtml
@model CapstoneProject.Models.Employee

@{
    ViewBag.Title = Model.FirstName + " " + Model.LastName;
}

<h2>Employee Details</h2>
<h4>@Model.FirstName @Model.LastName</h4>
@*<h4>@Html.ActionLink("View Evaluations??", "Details")</h4>*@

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)  @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            Cohort
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cohort.Name)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmployeeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CapstoneProject/Views/Employees/Edit.cshtml
@model CapstoneProject.Models.Employee

@{
    ViewBag.Title = "Edit | " + Model.FirstName + " " + Model.LastName;
}

<h2>Edit Employee</h2>
<h4>@Model.FirstName @Model.LastName</h4>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeeID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Email)

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CohortID, "CohortID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CohortID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CohortID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.SupervisorID, "SupervisorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupervisorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupervisorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerID, "ManagerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManagerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Delete", "Delete", new { id = Model.EmployeeID }) |
    @Html.ActionLink("Back to List", "Index")
</div>

CapstoneProject/Views/Employees/Index.cshtml
@model IEnumerable<CapstoneProject.Models.Employee>

@{
    ViewBag.Title = "Employee Index";
}

<h2>Employees</h2>
<h4>@Html.ActionLink("Upload Employee Data", "UploadData")</h4>
<h4 class="alert-success">@TempData["DeleteSuccess"]</h4>
<h4 class="alert-success">@TempData["EditSuccess"]</h4>
<h4 class="alert-success">@TempData["EmailSuccess"]</h4>
<br/>

<table class="table">
    <tr>
        <th>
            <label>Name</label>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            <label>Cohort</label>
        </th>
        <th>
            <label>Account Status</label>
        </th>
        <th>
            <label>Action</label>
        </th>
    </tr>

@foreach (var item in Model) {
    @Html.HiddenFor(modelItem => item.EmployeeID)
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LastName),
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cohort.Name)
        </td>
        <td>
            @if (item.EmailConfirmed)
            {
                <label class="alert-success">Email Confirmed</label>
            }
            else
            {
                <label class="alert-warning">Pending</label>
                <label>(</label>
                @Html.ActionLink("Notify", "SendPasswordCreationEmail", "Employees", new {id = item.EmployeeID}, null)
                <label>)</label>
            }
        </td>
        <td>
            @Html.ActionLink("View", "Details", new {id = item.EmployeeID}) |
            @Html.ActionLink("Edit", "Edit", new {id = item.EmployeeID}) |
            @Html.ActionLink("Delete", "Delete", new {id = item.EmployeeID})
        </td>
    </tr>
}

</table>

CapstoneProject/Views/Employees/UploadData.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "Upload Employee Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upload Employee Data</h2>
<h4 class="alert-warning">@ViewBag.Duplicates</h4>

@using (Html.BeginForm("UploadData", "Employees", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <br />
    <div class="form-group">
        <input type="file" id="dataFile" name="upload" />
    </div>

    <div class="form-group">
        <input type="submit" value="Upload" class="btn btn-default" />
    </div>

    <br />

    if (Model != null && Model.Rows.Count > 0)
    {
        <h4 class="alert-success">Employees Uploaded:</h4>
        <table class="table">
            <thead>
            <tr>
                @foreach (DataColumn col in Model.Columns)
                {
                    <th>@col.ColumnName</th>
                }
            </tr>
            </thead>
            <tbody>
            @foreach (DataRow row in Model.Rows)
            {
                <tr>
                    @foreach (DataColumn col in Model.Columns)
                    {
                        <td>@row[col.ColumnName]</td>
                    }
                </tr>
            }
            </tbody>
        </table>
    }
    if (Model != null && Model.Rows.Count == 0)
    {
        <p class="alert-warning">No employees were added.</p>
    }
}

<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>